const descriptions = [
  "The First Doctor was an unreadable, guarded figure who was, at first, slow to trust newcomers who learnt of him, but once his trust had been earned, he would show another side of himself as a staunch anti-authoritarian with a mischievous streak. This Doctor was often irascible. He made his anger obvious. He was protective of the young women he took on as companions; they reminded him of his granddaughter, Susan. This Doctor was a brilliant, often short-tempered scientist and keen strategist. He used his signet ring to help get himself through ordeals due to his physical age impeding him. He stole a TARDIS and took his granddaughter with him, joyriding through all space and time, without a clue as to how to drive the thing.",
  "The Second Doctor, in contrast, was warm and wise. He was as surprised and frightened of alien menaces as those who faced them with him. He had a knack for manipulation and deception, and especially enjoyed to play a buffoon in order to trick his opponents into underestimating him so that he could better carry out his plans. His predecessor would refer to him as a \"clown\" due to his bumbling nature. He loved tootling on his recorder and carried around a 500-year diary, trying to record his travels, but ended up discarding it. He wore a big fur coat that dwarfed him, tying it closed with twine. A \"cosmic hobo,\" he was forever getting himself in and out of trouble.",
  "The Third Doctor was a more dashing figure than his predecessors. He was described by his first incarnation as a \"dandy\". (TV: The Three Doctors) He had a penchant for inventing gadgets and was skilled at martial arts, particularly Venusian aikido, and owned a vintage car named Bessie. His initially contentious relationship with Brigadier Lethbridge-Stewart softened into a close friendship during his exile on Earth, lasting through his future regenerations, despite not always agreeing with his actions. (TV: Doctor Who and the Silurians) He also displayed great affection for his female companions, particularly Jo Grant. He was a gallant action hero who was very protective of his companions.",
  "The Fourth Doctor was more eccentric than his previous incarnations. Rarely without his long scarf, he carried jelly babies in his pockets, using them as bluffs, gifts and distractions—and occasionally snacks. He relied on his considerable charm, luck, and experience to get through bad situations. Although he retained his fondness for Earth (TV: The Stones of Blood), he ended his regular association with UNIT almost immediately upon his regeneration and only occasionally returned to the planet. However, he had not properly resigned from the position. (TV: Pyramids of Mars) He hated to work and preferred travelling (TV: Robot) but liked history. He enjoyed the company of a wide range of individuals, such as Sarah Jane Smith, aide to his previous self, (TV: Robot) Leela, a savage, (TV: The Face of Evil) K9, a robot dog, (TV: The Invisible Enemy) and even a fellow Time Lord in Romana. (TV: The Ribos Operation)",
  "The Fifth Doctor was fond of cricket and wore a stick of celery on his lapel. After a difficult regeneration, this Doctor displayed energy, compassion and innocence not seen in his predecessors. His character was very human and vulnerable. Like them, he used improvisation as the best way out of a tricky situation. The Fifth Doctor was the first incarnation since the First Doctor to go \"hands free\" and forgo the usage of a sonic screwdriver after having it destroyed. He occasionally wore glasses, even though he didn't need them; he only wore them to make himself look clever. (TV: Time Crash) He was the first Doctor to sacrifice himself for another, when he and Peri Brown were dying from Spectrox toxaemia; with only one dose of the antidote available, he gave her the cure rather than taking it himself.",
  "The Sixth Doctor was a grandiose and eloquent incarnation. He sported a multi-coloured wardrobe that looked like it was designed by Christian Lacroix; it was often commented upon, occasionally leading to him being mistaken for a jester. This Doctor loved a good quote, often making one he deemed appropriate during an adventure. He also proved to have great acting skills on numerous occasions. (TV: Mindwarp, The Ultimate Foe) His manic personality and acerbic wit could shade into moral passion, but his lack of concern for little things disgusted his companions. He was also capable of violent action, much more so than his past lives, and of killing without remorse when his life was threatened. (TV: The Two Doctors) Like the Fourth Doctor, he spent most of his travels with a single companion.",
  "The Seventh Doctor had a voice touched by a Scottish burr. A keen strategist and scientist and especially early in his life, lighthearted, this Doctor was a planner of the highest order. Embracing the complexities of time travel and his ability to manipulate and plan for the future, the Seventh fully embraced his role of Time Lord, even if it risked alienating his companions. (TV: The Curse of Fenric) However, he wished to help heal psychological scars from which his companions suffered. (TV: The Greatest Show in the Galaxy, Ghost Light)",
  "The Eighth Doctor showed a romantic and sensitive side not displayed by previous Doctors. Less morally flexible than his immediate predecessor, the Eighth Doctor suffered from bouts of amnesia, first after his regeneration and again after Gallifrey was destroyed following the War with the Enemy. (PROSE: The Ancestor Cell) He broke down after the death of his Great-Grandson Alex Campbell and companion Lucie Miller, who died defeating a Dalek invasion of Earth. (AUDIO: To the Death) Unlike other Doctors, the Eighth spent his travels crossing between parallel universes (AUDIO: Zagreus, PROSE: Time Zero) and amidst time paradoxes, making his personal timeline hard to piece together. (PROSE: Interference - Book One, Interference - Book Two, AUDIO: Storm Warning)",
  "The Ninth Doctor considered himself the sole Time Lord survivor of the Time War (he spent his life thinking that he was responsible for destroying the Time Lords). He displayed much of the playfulness of his previous incarnations, but was emotionally and psychologically scarred by the war and his role in it, which sometimes resulted in a detachment that was interpreted by some as cruelty. (TV: The End of the World, Dalek) When asked about his voice and accent, he responded, \"Lots of planets have a North.\" (TV: Rose) He cared deeply for Rose; he began to heal thanks to her. (TV: Dalek) He also made dry jokes when facing danger or to diffuse tension. The Ninth Doctor ultimately sacrificed himself to save Rose's life, not only proving his affection for her, but allowing him to make peace with his past. (TV: The Parting of the Ways)",
  "The Tenth Doctor had a manic personality with a fondness for human pop culture references. However, his more outgoing personality traits largely existed to hide leftover emotional trauma from the Time War. While he had a bright, playful side, darker traits occasionally emerged. (TV: The Christmas Invasion, Tooth and Claw, School Reunion, The Runaway Bride) He continued his previous incarnation's love for Rose Tyler, though he was unable or unwilling to express his exact feelings. (TV: Doomsday; Journey's End) He experienced other romances on occasion, including with historic figures Madame de Pompadour (TV: The Girl in the Fireplace) and Queen Elizabeth I. (TV: The End of Time, The Day of the Doctor) However, they all ended badly. He was also the first Doctor to explicitly fear and dodge regeneration, because he had grown attached to his attributes and felt like it was a form of death and loss of identity; indeed, he is the first Doctor to actually undergo a regeneration (after being shot by a Dalek) yet retain his appearance and personality (TV: Journey's End; confirmed as a regeneration in TV: The Time of the Doctor). When the time came for him to fully regenerate, he was completely heartbroken before accepting his destiny. (TV: The End of Time)",
  "The Eleventh Doctor exhibited a renewed youthful enthusiasm for adventure. He could quickly turn frantically angry and ruthless when events demanded. (TV: The Eleventh Hour, The Beast Below, A Town Called Mercy) Like his Second and Seventh selves before him, he was a cunning schemer, executing temporally complex plans and misdirections to achieve victory against his enemies. (TV: Day of the Moon, A Good Man Goes to War, The Wedding of River Song) He frequently referred to himself as being old, showing his age on more than a few occasions. (TV: Vincent and the Doctor, The Big Bang, The Impossible Astronaut, Closing Time) Through his marriage to River Song, he found a sense of family again with her and his in-laws, and was distraught when circumstances separated him from them. (TV: The Power of Three, The Angels Take Manhattan, The Name of the Doctor) Some events still provided painful reminders of his role in the Time War. (TV:The Rings of Akhaten, The Time of the Doctor, et al.) He was the final incarnation before the Time Lords granted him a new regeneration cycle.",
  "The Twelfth Doctor displayed an acerbic wit coupled with sarcasm. Like his seventh incarnation, he was manipulative and practical to a fault. He lacked much of the empathy present in his immediate predecessors, and as a result found himself coming off as callous or uncaring on many occasions. In spite of this he shared the Eleventh Doctor's lack of tact and odd behaviour. He had a tendency to brush off death around him, in order to focus on the task at hand. However, because of this he expressed doubt as to whether he was a \"good\" man. (TV: Into the Dalek) He eventually accepted that he wasn't a good man, but decided he wasn't a bad one either, being just \"an idiot with a box.\" He was also not completely uncaring as shown when Clara Oswald tried to force him to help her save Danny Pink and he stated afterwards that even though she betrayed him in the worst way, it didn't change his willingness to help her or how much he cared. (TV: Dark Water, Death in Heaven) This incarnation had the same face as Lobus Caecilius, a man whose family he once saved from the eruption of Pompeii (TV: The Fires of Pompeii); the Doctor did not remember this until following the (initial) death of Ashildr he had an epiphany about his purpose (TV: The Girl Who Died). Although less affectionate than his predecessor, at one point dismissing his eleventh incarnation's infatuation with Clara as \"a mistake\", the Doctor and Clara's relationship, especially after the death of Danny Pink, deepened to the point where he became obsessed with her safety and threatened all of space and time on a 4.5-billion-year gambit to undo her subsequent death; although he successfully rendered her functionally (if temporarily) immortal, he was forced to erase most of his substantial memories of her. (TV: Face the Raven; Heaven Sent; Hell Bent) This incarnation subsequently used the hard-earned lesson of the loss of Clara to finally resolve his relationship with River Song, allowing her to finally meet her own fate after having put it off since his eleventh incarnation. (TV: The Husbands of River Song)"
];

const captions = i => descriptions[i].match(/The \w+ Doctor/);

const actors = [
  "William Hartnell",
  "Patrick Troughton",
  "Jon Pertwee",
  "Tom Baker",
  "Peter Davison",
  "Colin Baker",
  "Sylvester McCoy",
  "Paul McGann",
  "Christopher Eccleston",
  "David Tennant",
  "Matt Smith",
  "Peter Capaldi",
];

export {descriptions, captions, actors};